site_name: ТЛТ ПРО
site_url: https://knowledge-base-tltpro/tltpro
theme:
    name: material
    palette:
        primary: purple
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - toc.follow
        
        
nav:
  - Главная: main.md
  - Цель компании: 
    - Цель компании: purpose.md
    - Идеи о парнерстве: ideas.md
    - Руководители: leaders.md
  - План отбора и введения новых сотрудников:
    - Введение разработчиков: developers.md
    - Введение стажеров: interns.md
  - Правила работы:
    - Основные положения:
      - Финансы: finance.md
      - Корпоративный чат:
        - Корпоративный чат: corporate chat.md
        - Разговорная открытость: conversational openness.md
      - Контроль воронки продаж: sales funnel control.md
      - Оценка проекта: project evaluation.md
    - Ведение проекта:
      - Взаимодействие с заказчиком: interaction with the customer.md
      - Главные ошибки: major mistakes.md
      - ЧАВО: FAQ.md
      - План работ: work plan.md
      - Правила разработки:
        - Обсуждение проекта: project discussion.md
        - Team lead: teamlead.md
        - Постановка задач: setting tasks.md
        - Домен/Сервер: domain server.md
        - Git: git.md
        - Figma: figma.md
        - Видео: videos.md
    - Супервайзинг:
      - Супервайзеры: supervisors.md
      - Основные положения: supervising.md
  - Вспомогательные ресурсы и программы:
    - Markdown: markdown.md
    - MkDocs: mkdocs.md
  
